#!/usr/bin/env python3
"""Regenerate the reviewed inventory of SQLx calls that remain runtime checked."""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/development/sqlx-runtime-queries.md"
PATTERN = re.compile(
    r"sqlx::(query_as|query_scalar|query)(?P<generic>::<[^\n]+?>)?\s*\("
)


def reason(kind: str, line: str) -> tuple[str, str]:
    if "AssertSqlSafe" in line or line.rstrip().endswith("(sql)"):
        return (
            "dynamic SQL",
            "The statement text is assembled at runtime; SQLx macros require a literal.",
        )
    if any(command in line for command in ("SAVEPOINT", "ROLLBACK TO", "RELEASE SAVEPOINT")):
        return (
            "transaction control",
            "This is transaction protocol, not a row query SQLx can describe and cache.",
        )
    if kind == "query_as":
        return (
            "row mapping",
            "The shared FromRow contract includes custom PostgreSQL enums, tsvector, tuple output, or synthetic fields and needs an explicit projection before macro conversion.",
        )
    if kind == "query_scalar":
        return (
            "scalar mapping",
            "The scalar is a custom PostgreSQL enum or comes from a CTE/aggregate whose nullability needs an explicit SQLx override.",
        )
    return (
        "executor binding",
        "The statement participates in a transaction/helper binding path that uses custom enum parameters or runtime executor composition; convert with its owning DB module.",
    )


rows: list[tuple[str, str, str]] = []
for relative in (Path("crates/api/src"), Path("crates/db/src")):
    for path in sorted((ROOT / relative).rglob("*.rs")):
        for number, line in enumerate(path.read_text().splitlines(), 1):
            for match in PATTERN.finditer(line):
                category, explanation = reason(match.group(1), line)
                rows.append(
                    (
                        f"{path.relative_to(ROOT)}:{number}",
                        category,
                        explanation,
                    )
                )

content = """# SQLx Runtime Query Inventory

Generated by `python3 scripts/sqlx-runtime-inventory.py`. Each entry is an explicit
exception to the compile-time macro policy recorded in ADR 0010. CI regenerates
this file and fails on drift, so adding a runtime query requires reviewing and
committing its reason rather than silently bypassing offline checking.

| Location | Class | Reason |
| :--- | :--- | :--- |
"""
content += "".join(
    f"| `{location}` | {category} | {explanation} |\n"
    for location, category, explanation in rows
)
content += f"\n**Total runtime-checked exceptions: {len(rows)}.**\n"
OUTPUT.write_text(content)
print(f"wrote {OUTPUT.relative_to(ROOT)} with {len(rows)} entries")
